# Generated by Django 5.0.1 on 2024-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SP500Stocks',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('slope', models.DecimalField(decimal_places=5, max_digits=10)),
                ('intercept', models.DecimalField(decimal_places=5, max_digits=15)),
                ('rsi', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pe_ratio', models.DecimalField(decimal_places=5, max_digits=10)),
                ('score', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
