# Generated by Django 5.0.1 on 2024-04-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp500stocks',
            name='intercept',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sp500stocks',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sp500stocks',
            name='rsi',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sp500stocks',
            name='score',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sp500stocks',
            name='slope',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
