# Generated by Django 5.0.1 on 2024-04-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_sp500stocks_intercept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sp500stocks',
            name='symbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
