# Generated by Django 5.0.1 on 2024-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_sp500stocks_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOWStocks',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slope', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('intercept', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NASDAQStocks',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slope', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('intercept', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RUSSELLStocks',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slope', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('intercept', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
            ],
        ),
    ]
