# Generated by Django 5.0.1 on 2024-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockdata_delete_russellstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('symbol', 'date')},
        ),
    ]
